version: '3.4'

services:
  api:
    build: .
    command: npm run start:dev
    restart: always
    environment:
      - FORCE_COLOR=3
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - 3005:${PORT}
    networks:
      - nestjs-boilerplate-api

networks:
    nestjs-boilerplate-api:
      driver: bridge