name: Build and Deploy

on:
  pull_request:
    branches: [main]

jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Env
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Tests
        run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from api-test --timeout 600

  BUILD:
    runs-on: ubuntu-latest
    needs: [TEST]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        run: sh docker/build.sh

      - name: 🔀 Merge Pull Request
        uses: BaharaJr/merge-pr@0.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
